### ISSUE TITLE
Change the config.output.publicPath to localhost but not working

### ISSUE THREAD

**Issue by KyleMoneris** [afonsojramos/microfrontend-nextjs#1]
### 🔍 Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### 📝 Description

I created stackOverFlow question here https://stackoverflow.com/questions/72450399/micro-frontend-routing-issue-with-next-js

### 🪜 Steps To Reproduce

1. Change the `config.output.publicPath` to 'http://localhost:3001/_next/' in app1's `next.config.js` file
2. Change the `config.output.publicPath` to 'http://localhost:3002/_next/' in app2's `next.config.js` file
3. Change the two `script` tag's reference to "http://localhost:3001/_next/static/runtime/app1RemoteEntry.js" and "http://localhost:3002/_next/static/runtime/app2RemoteEntry.js"
4. Restart the three application and don't see the app1 and app2 page.

### ℹ System Info

```Markdown
windows system with node v16.14.0
```

### 📸 Screenshots

![image](https://user-images.githubusercontent.com/106557014/171219735-aa8df6a6-5c30-42cf-b39f-cc65a4fc0413.png)
![image](https://user-images.githubusercontent.com/106557014/171219776-f8f5d9e5-890d-40a5-bd9e-1cea51e0cdd9.png)
![image](https://user-images.githubusercontent.com/106557014/171219837-9fabca11-caac-4038-bca6-08555dfc560b.png)

**Comment by afonsojramos** [comment]
You do not need to change anything, the repository is working as it is for localhost development. Can you try that instead?
